name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: notifications
          POSTGRES_PASSWORD: password
          POSTGRES_DB: notifications_db

      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Wait for services
        run: |
          # Ожидание, пока Postgres и RabbitMQ будут готовы
          for i in {1..30}; do
            nc -z db 5432 && nc -z rabbitmq 5672 && break
            echo "Waiting for services..." && sleep 1
          done

      - name: Run Unit Tests
        env:
          DATABASE_URL: postgres://notifications:password@localhost:5432/notifications_db
          RABBITMQ_URL: amqp://user:password@localhost:5672
        run: npm test -- tests/unit/gateway.test.js
